#
# Blog Settings
#
name: Dariel Marlow
description:
url: http://dmarlow.github.io
title: Dariel Marlow
subtitle: I never finish anyth
#gravatar_url: 
subscribe_rss: http://feeds.feedburner.com/DarielMarlow
encoding: utf-8

# Github repositories
github_user: dmarlow
github_repo_url: https://github.com/dmarlow/dmarlow.github.io/

# Twitter
twitter_user: _dmarlow_
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: dmarlow
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-53098809-1
google_analytics_domain: dmarlow.github.io


#
# Jekyll Settings
#
markdown: redcarpet
pygments: false
highlighter: rouge
permalink: /:year/:month/:title.html
paginate: 20
paginate_path: "page/:num"
category_dir: categories
exclude: [vendor]
